name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/core/**'
      - 'packages/cli/**'
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/core/**'
      - 'packages/cli/**'
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build core package
      run: |
        cd packages/core
        pnpm build
    
    - name: Build CLI package
      run: |
        cd packages/cli
        pnpm build
    
    - name: Run core tests
      run: |
        cd packages/core
        pnpm test
    
    - name: Run CLI tests
      run: |
        cd packages/cli
        pnpm test
    
    - name: Run linting
      run: pnpm lint
    
    - name: Type check
      run: pnpm type-check
