name: Blockchain CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
      - 'packages/core/src/stellar/**'
      - 'packages/core/src/blockchain/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
      - 'packages/core/src/stellar/**'
      - 'packages/core/src/blockchain/**'

jobs:
  blockchain:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Build credit-score contract
      run: |
        cd contracts/credit-score
        cargo build --release
    
    - name: Build fraud-detect contract
      run: |
        cd contracts/fraud-detect
        cargo build --release
    
    - name: Build common-utils contract
      run: |
        cd contracts/common-utils
        cargo build --release
    
    - name: Test credit-score contract
      run: |
        cd contracts/credit-score
        cargo test
    
    - name: Test fraud-detect contract
      run: |
        cd contracts/fraud-detect
        cargo test
    
    - name: Test common-utils contract
      run: |
        cd contracts/common-utils
        cargo test
    
    - name: Run clippy
      run: |
        for contract in contracts/*/; do
          echo "Running clippy on $contract"
          cd "$contract"
          cargo clippy -- -D warnings
          cd ../..
        done
    
    - name: Check formatting
      run: |
        for contract in contracts/*/; do
          echo "Checking format for $contract"
          cd "$contract"
          cargo fmt -- --check
          cd ../..
        done
