name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-core:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run core tests
      run: |
        cd packages/core
        pnpm test
    
    - name: Run CLI tests
      run: |
        cd packages/cli
        pnpm test
    
    - name: Run example tests
      run: |
        cd examples/credit-scoring-app
        pnpm test
      continue-on-error: true

  test-contracts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Test all contracts
      run: |
        for contract in contracts/*/; do
          echo "Testing $contract"
          cd "$contract"
          cargo test
          cd ../..
        done

  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run integration tests
      run: pnpm test:integration
      env:
        STELLAR_NETWORK: testnet
        AI_API_KEY: ${{ secrets.AI_API_KEY }}
